name: Deploy to Server

on:
  pull_request:
    # Change to merge when implemented (still beta)
    types: [closed]
    branches:
      - testing

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.project }}
        script: |
           r10k deploy environment testing -pv
