name: Deploy to Server

on:
  pull_request:
    # Change to merge when implemented (still beta)
    types: [closed]
    branches:
      - testing

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.project }}
        script: |
          cd ${{ secrets.deploy_dir }}
          . venv-prod/bin/activate
          cd website
          git pull
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r prod_requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
