
name: Deploy to Server2

on: [push]
 

jobs:
 build:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.4
      with:
       host: ${{ secrets.PROXY_HOST }}
       username: ${{ secrets.PROXY_USERNAME }}
       key: ${{ secrets.TAFI_LOGIN }}
       port: ${{ secrets.PROXY_PORT }}
       script: |
         echo "ffsffssaffffffs"


