
name: Deploy to Server2

on: [push]

jobs:
  job:
    name: config
    steps:
      script: echo 'CASignatureAlgorithms +ssh-rsa' > /etc/ssh/sshd_config

  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.project }}
        port: ${{ secrets.port }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.TAFI.LOGIN }}
        proxy_port: ${{ secrets.PROXY_PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        script: |
          echo "ffss"
