
name: Deploy to Server2

on: [push]
 

jobs:
 build:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.4
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER }}
       key: ${{ secrets.PROJECT }}
       port: ${{ secrets.PORT }}
       use_insecure_cipher: true
       script: |
         echo "ffsffssffffff"


