
name: Deploy to Server2

on: [push]
 

jobs:
 build:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.4
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER }}
       key: ${{ secrets.ED25519 }}
       port: ${{ secrets.PORT }}
       proxy_host: ${{ secrets.PROXY_HOST }}
       proxy_username: ${{ secrets.PROXY_USERNAME }}
       proxy_key: ${{ secrets.TAFI.LOGIN }}
       proxy_port: ${{ secrets.PROXY_PORT }}
       script: |
         echo "ffsffssfffff"


